{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helios-frontend
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: {{ .Values.frontend.ingress.ingressClassName }}
  tls:
    - hosts: [{{ .Values.frontend.ingress.host }}]
      secretName: helios-frontend-tls
  rules:
    - host: {{ .Values.frontend.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.name }}
                port:
                  number: {{ .Values.frontend.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.demoApi.name }}
                port:
                  number: {{ .Values.demoApi.port }}
{{- end }}
