apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helios-platform.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helios-platform.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.configMap.logLevel | quote }}
  ENVIRONMENT: {{ .Values.configMap.environment | quote }}
  MEMORY_THRESHOLD_PERCENT: {{ .Values.selfHealingOperator.config.memoryThresholdPercent | quote }}
  RESTART_AFTER: {{ .Values.selfHealingOperator.config.restartAfter | quote }}
  MAX_FAILED_PODS_BEFORE_ROLLBACK: {{ .Values.selfHealingOperator.config.maxFailedPodsBeforeRollback | quote }}
  ROLLBACK_WINDOW: {{ .Values.selfHealingOperator.config.rollbackWindow | quote }}
  UNHEALTHY_NODE_CONDITIONS: {{ .Values.selfHealingOperator.config.unhealthyNodeConditions | join "," | quote }}
